### ISSUE TITLE
turtle has no attribute register_shape, listen, ontimer, onkey, etc

### ISSUE THREAD

**Issue by Stephenlaye2** [skulpt/skulpt#1388] opened 2021-10-14 09:12 UTC
I am trying to create a turtle game. the game works perfectly when I run it locally. However, when I use Skulpt, I keep getting lot of attribute error. I'm trying to use arrow keys to play the game so I use turtle.listen(), but I keep getting attribute errors. I also can't register the shape of my characters with the gif, which I have no problem with when I run the game in Python locally. I had to use square and circle shape instead. That works, but I still can't play the game.

This is what I want the game to look like

![maze_game](https://user-images.githubusercontent.com/32752271/137287861-d74f229f-e7e0-45d1-8e6f-45ff2135a0b7.png)

This is what I have modified it into due to attribute errors from Skulpt. I still can't play it though.
![maze_browser](https://user-images.githubusercontent.com/32752271/137288435-c1206d4e-bb9b-40ab-a3a3-d5c65e01d274.png)

Here is the code:

````
import turtle
import math
import random
#import os.path


screen = turtle.Screen()

screen.bgcolor('black')
screen.title('MAZE GAME')
screen.setup(800, 800)
#screen.tracer(0)

Turtle = turtle.Turtle
# Pen class as subclass of Turtle

class Pen(Turtle):
  # create constructor
  def __init__(self):
    Turtle.__init__(self)
    self.shape('square')
    self.color('white')
    self.penup()
    self.speed(0)

# Create a warrior class as subclass of the Turtle
class Warrior(Turtle):
  def __init__(self):
    Turtle.__init__(self)
    self.shape("square")
    self.color('cyan')
    self.penup()
    self.speed(0)
    self.wealth = 0
  
  def move(self, x, y):
    if (x, y) not in walls:
      self.goto(x, y)

  def move_up(self):
    coord_x = warrior.xcor()
    coord_y = warrior.ycor() + 24
    self.move(coord_x, coord_y)
    

  def move_down(self):
     coord_x = warrior.xcor()
     coord_y = warrior.ycor() - 24
     self.move(coord_x, coord_y)

  def move_left(self):
     coord_x = warrior.xcor() - 24
     coord_y = warrior.ycor()
     
     self.move(coord_x, coord_y)
     

  def move_right(self):
     coord_x = warrior.xcor() + 24
     coord_y = warrior.ycor() 
    
     self.move(coord_x, coord_y)
  
  def is_collide(self, the_treasure):
    # using distance between two point formula d(p,q) = sqrt((x2-x1)^2 + (y2-y1)^2)
    x = self.xcor() - the_treasure.xcor()
    y = self.ycor() - the_treasure.ycor()
    distance = math.sqrt((x ** 2) + (y ** 2))
    if distance <= 5:
      return True
    else:
      return False


# Create treasure class
class Treasure(Turtle):
  def __init__(self, x, y):
    Turtle.__init__(self)
    self.shape('circle')
    self.color('gold')
    self.penup()
    self.speed(0)
    self.goto(x, y)
    self.wealth = 100
    

  def destroy(self):
    self.goto(2000, 2000)
    self.hideturtle()
  
# Create Enemy class
class Monster(Turtle):
  def __init__(self, x, y):
    Turtle.__init__(self)
    self.shape('circle')
    self.color('red')
    self.penup()
    self.speed(0)
    self.wealth = 25
    self.goto(x, y)
    self.direction = random.choice(["Up", "Down", "Right", "Left"])

    

  # Calculate the distance between the warrior and monster
  def is_nearby(self, the_warrior):
    x = self.xcor() - the_warrior.xcor()
    y = self.ycor() - the_warrior.ycor()
    distance = math.sqrt((x ** 2) + (y ** 2))
    return distance

  def motion(self):
    drtn = self.direction
    if drtn == "Right":
      point_x = 24
      point_y = 0
   
    elif drtn == "Left":
      point_x = -24
      point_y = 0
     
    elif drtn == "Up":
      point_x = 0
      point_y = 24
    elif drtn == "Down":
      point_x = 0
      point_y = -24
    else:
      point_x = 0
      point_y = 0
    
    coord_x = self.xcor() + point_x
    coord_y = self.ycor() + point_y

    if(coord_x, coord_y) not in walls:
      self.goto(coord_x, coord_y)
    else:
      self.direction = random.choice(["Up", "Down", "Right", "Left"])
    
    # Set random motion time to keep monsters moving
    turtle.ontimer(self.motion, t=random.randint(200, 500))

    # Make the monster aware of the warrior proximity
    if self.is_nearby(warrior) <= 50:
      if warrior.xcor() > self.xcor():
        self.direction = "Right"
      elif warrior.xcor() < self.xcor():
        self.direction = "Left"
      elif warrior.ycor() > self.ycor():
        self.direction = "Up"
      elif warrior.ycor() < self.ycor():
        self.direction = "Down"



# Initialise list
levels = ['']
walls = []
treasures = []
monsters = []

level = [
  'KKKKKKKKKKKKKKKKKKKKKKKKK',
  'KW KKKKKKK    M     KKKKK',
  'K  KKKKKKK  KKKKKK  KKKKK',
  'K       KK  KKKKKK  KKKKK',
  'K       KK  KKK        KK',
  'KKKKKK  KK  KKK        KK',
  'KKKKKK  KK  KKKKKK  KKKKK',
  'KKKKKK  KK    KKKK   KkkK',
  'K  KKK     M  KKKKkk   KK',
  'K  KKK   KKKKKKKKKKKKKGKK',
  'K          KKKKKKKKKKKKKK',
  'K    M            KKKKKKK',
  'KKKKKKKKKK    M  KKKKK  K',
  'KKKKKKKKKKKKK    KKKKK  K',
  'KKK  KKKKKKKK           K',
  'KKK                    GK',
  'KKK        KKKKKKKKKKKKKK',
  'KKKKKKKKK  KKKKKKKKKKKKKK',
  'KKKKKKKKK               K',
  'KK  KKKKK G           M K',
  'KK  KKKKKKKKKKKKKK  KKKKK',
  'KK   YKKKKKKKKKKKK  KKKKK',
  'KK          KKKK        K',
  'KKKK  G                 K',
  'KKKKKKKKKKKKKKKKKKKKKKKKK',
]

# Append level to levels
levels.append(level)

# Setup level
def setup_maze_level(levl_lst):
  for i in range(len(levl_lst)):
    for j in range(len(levl_lst[i])):
      char = levl_lst[i][j]

      # Specify the cordinates that the Pen will be positioned
      coord_x = -288 + (j * 24)
      coord_y = 288 - (i * 24)
      

      # Pen should go to the specified coordinates if the character is K
      if char == 'K':
        pen.goto(coord_x, coord_y)
        pen.stamp()
        walls.append((coord_x, coord_y))
      
      # Pen should go to the P(warrior) coordinate if the character is P
      if char == 'W':
        warrior.goto(coord_x, coord_y)
        # warrior.stamp()
      if char == 'G':
        treasures.append(Treasure(coord_x, coord_y))
      
      if char == 'M':
        monsters.append(Monster(coord_x, coord_y))

# Instantiate Pen, warrior class
pen = Pen()
warrior = Warrior()

# Call the setup_maze_level function
setup_maze_level(levels[1])

# Enable turtle to use keyboard arrow key - Keyboard Binding
turtle.listen()
turtle.onkey(warrior.move_up, 'Up')
turtle.onkey(warrior.move_down, 'Down')
turtle.onkey(warrior.move_left, 'Left')
turtle.onkey(warrior.move_right, 'Right')

# Turn screen updates off
screen.tracer(0)


# Set the time for monsters to start moving
for monster in monsters:
  turtle.ontimer(monster.motion, t=300)


# The main Game Loop
while True:
  for treasure in treasures:
    if warrior.is_collide(treasure): 
      warrior.wealth += treasure.wealth
      print(f'You collected {warrior.wealth} gold!')
      treasure.destroy()
      treasures.remove(treasure)
      

  for monster in monsters:
    # Destroy and remove monster nearest to the collected treasure
    
    if warrior.is_collide(monster):
      warrior.wealth -= monster.wealth
  # Enable screen update
  screen.update()
````

**Comment by Stephenlaye2** [comment] 2021-10-15 08:30
> All these attributes are in the `lib/turtle.js` . Read it carefully.

Thanks @alexwenbj. Any chance you could provide me the 'lib' directory.

**Comment by s-cork** [comment] 2021-10-19 14:44
this is a duplicate of #1392

**Closed as completed by s-cork** 2021-10-19 14:44 UTC
Labels: duplicate, turtle
