### ISSUE TITLE
Unable to kill skulpt program

### ISSUE THREAD

**Issue by jasoneaston** [skulpt/skulpt#1295] opened 2021-04-22 19:39 UTC
Hi all,

I'm trying to implement an option for multiple code editors on a single webpage using skulpt. Unfortunately it seems like skulpt can handle just one execution of code at a time. This is ok for most scenarios, but it becomes a problem when we have infinite while loops or a long time.sleep.

Is there a way to stop the execution of skulpt dead in its tracks right away? Ideally there should be a way to call Sk.killAllExecution(function when kill is complete).

One solution proposed was to use the Sk.execLimit = 1; strategy, but this is not very clean and it results in sketchy behavior when you have time.sleep(10) for example. It takes 10 seconds before your code can be stopped which isn't very nice for the user.

Any ideas?

Thank you.

**Comment by alexwenbj** [comment] 2021-04-23 05:17
see #1197, maybe it helps.

**Comment by s-cork** [comment] 2021-04-23 06:28
another related discussion #1289

**Comment by nerdschmiede** [comment] 2021-05-12 10:28
you can use yieldLimit
https://stackoverflow.com/questions/54503455/how-to-stop-a-script-in-skulpt 
https://jsfiddle.net/sc549/bjLuq5s7/

**Comment by s-cork** [comment] 2021-06-11 02:19
closing this - seems to be a duplicate of other issues

**Closed by s-cork** 2021-06-11 02:19 UTC
