### ISSUE TITLE
Long loop breaks suspensions

### ISSUE THREAD

**Issue by cgibin** [skulpt/skulpt#875] opened 2019-05-22 17:44 UTC
Hello everyone.
I am facing weird problem using suspensions. I have this problem with python->js code generator, but reduced it to make it more clear.

This code represents suspensions mehanic in a nutshell.

```javascript
(function() {
  var _module = function() {
    const _scope = function() {
      var a = 0,
        block = 0;
      var suspend = function() {
        var context = {};
        context.a = a;
        context.block = block;
        context.resume = function() {
          _scope.context = context;
          return _scope();
        };
        _scope.context = context;
        return context;
      };
      var awake = function() {
        context = _scope.context;
        delete _scope.context;
        //_scope.context = undefined;
        a = context.a;
        block = context.block;
      };
      if (_scope.context !== undefined) {
        awake();
      }
      while (true) {
        switch (block) {
          case 0:
            block = 1;
            return suspend();
          case 1:
            block = 0;
            if (a++ > 10000) {
              return;
            }
            continue;
        }
      }
    };
    return _scope();
  };

  var runMod = function() {
    var susp = _module();
    var nSteps = 0;
    while (susp) {
      susp = susp.resume();
      if (!(++nSteps % 1000)) {
        console.log(nSteps, susp);
      }
      if (nSteps > 100000) {
        console.log("aborted");
        break;
      }
    }
    console.log("complete", nSteps);
  };

  runMod();
})();
```
This code should iterate 10000 times and return
Instead, it runs infinitely in Chrome(I added sane check, and it stops after abnormal amount of steps), but works fine in Firefox
If I reduce iterations to 100 it works in both browsers(both up to date)
When it hangs, variable "a" stuck at same value without increment(about 1000 on my cpu).
I found that problem in this line of code "delete _scope.context", replacing it with "_scope.context = undefined" fixes this bug
The problem exists in code generated by skulpt, if you need I can provide generated code

The code is here https://jsfiddle.net/daborkpw/

Can you confirm this problem and restore faith in my sanity?

**Comment by bnmnetp** [comment] 2019-05-22 18:24
@meredydd @albertjan @rixner I have a feeling this is related to #868 which I can still reproduce in the very latest builds but forgot to reopen.  It also is reproducible in older builds so I don't think it has anything to do with the move to node.

**Comment by cgibin** [comment] 2019-05-22 19:48
Yes, #868 also related to this, I somehow missed that. I also originaly started to investigate this bug when one of our kids tried to draw circle by 1 degree steps. And it drew only partialy

**Comment by albertjan** [comment] 2019-05-23 07:07
I'm on the phone with the Vatican as we speak.

First I thought we were consuming the thread with the while loop so I put that in a setTimeout and the same thing happened but muuuuuchh slower. Which is even more mind boggling if you ask me. 

I'm gonna be investigating this a bit more but I think we might be fighting with some optimiser in v8 or something. Because it works on Firefox. 

I'm going to look if I can make the reproduction a little simpler even, and then maybe reach out to someone that works for v8/google to have a look at this. 

Here is a link to the jsbin I've been using for testing: https://jsbin.com/derihufore/edit?js,console

**Comment by albertjan** [comment] 2019-05-23 08:33
Hey @LeszekSwirski could you shine some light on this? 

https://jsbin.com/nuduhoq/edit?js,console I've whittled the example down a little in this jsbin.

It's like the `context` reference on the scope function gets frozen somehow, doesn't happen all the time. 

Should we open a bug report for v8?

**Comment by LeszekSwirski** [comment] 2019-05-23 15:41
I see it as working in latest canary, so probably this was a bug that was fixed in the last few versions. I'll try bisecting to see what it was exactly (and if it indeed is fixed).

**Comment by LeszekSwirski** [comment] 2019-05-23 15:42
Likely to be https://crbug.com/v8/9233 though

**Comment by albertjan** [comment] 2019-05-23 15:42
I'm on Chrome `Version 74.0.3729.169 (Official Build) (64-bit)`

**Comment by LeszekSwirski** [comment] 2019-05-23 15:44
Try canary, the fix I mentioned first landed in 76.0.3795.0

**Comment by albertjan** [comment] 2019-05-23 15:45
@LeszekSwirski that sounds very likely indeed, since swapping `delete` for `= undefined` fixes the bug.

**Comment by LeszekSwirski** [comment] 2019-05-23 15:50
Well, if it is that then a workaround got merged into 75, which is hitting stable soon, so this should go away with that.

**Comment by albertjan** [comment] 2019-05-23 16:01
@LeszekSwirski Thank you Sir! 🎩

@cgibin you were not crazy 😄 are you happy to close this?

**Comment by cgibin** [comment] 2019-05-24 05:43
I guess it's fine now, my only concern is that we are using sculpt in schools and sometimes version of browsers they use far from latest. So users might end locked up with version where bug still exists

**Comment by LeszekSwirski** [comment] 2019-05-24 05:53
It might not be crazy to use `scope.context = undefined` instead of `delete scope.context` anyway, to avoid a prototype walk when checking `scope.context`.

**Comment by cgibin** [comment] 2019-05-24 11:37
So should I make pr with fix , or what's you up to, @albertjan ?

**Comment by albertjan** [comment] 2019-05-24 19:34
@cgibin please do submit a PR 😄

**Closed** 2019-05-27 22:43 UTC
