### ISSUE TITLE
Sk.builtin.str for single character

### ISSUE THREAD

**Issue by OctopussyO** [skulpt/skulpt#1467] opened 2022-10-14 12:15 UTC
Hi!

Can you explain me, how does it possible?
It seems like for single character string constructor returns the whole Sk.builtin
![image](https://user-images.githubusercontent.com/43892676/195844534-be40daed-2f31-4ed1-abd7-4d055bb362d7.png)
![image](https://user-images.githubusercontent.com/43892676/195843816-ee80209d-27f1-4892-9034-1d7c0c43276b.png)

skulpt@1.2.0

@s-cork maybe you could help?   (´• ω •)ﾉ

**Comment by s-cork** [comment] 2022-10-14 14:59
I can't reproduce this I'm afraid.
skulpt.org currently runs v1.2.0 and that code snippet does what it's supposed to in the browser console.
As it does if I build 1.2.0 from source.

Please send a codesandbox, or similar, that demonstrates the issue.

**Comment by s-cork** [comment] 2022-11-11 08:46
closing - please re-open if you can post a demonstration of the issue

**Closed by s-cork** 2022-11-11 08:46 UTC
