### ISSUE TITLE
Some character make result wrong in format.

### ISSUE THREAD

**Issue by Dustyposa** [skulpt/skulpt#871] opened 2019-05-22 02:52 UTC
When I use print to output some Chinese. I already set  `__future__=Sk.python3`
e.g
```
print("这是{}".format("中文"))
>>> 这是中文
```
But when I append some character, for example:
`\n`
```
print("这是\n{}".format("中文"))
>>>è¿æ¯
>>>中文
```
This caused an coding error.

**Comment by albertjan** [comment] 2019-05-22 07:52
Wow ok yeah, this will need some investigation. 

Does this work? `print("这是\n中文")` 

If so the problem is in `.format` which is here: https://github.com/skulpt/skulpt/blob/master/src/formatting.js

**Comment by Dustyposa** [comment] 2019-05-22 08:32
```print("这是\n中文")
>>> 这是
>>> 中文
```
This will work.
I doubt formatting way have a bug.
Ok, "\n" should be make this problem. I will try to check this file.
In earlier, I looked for the wrong file... https://github.com/skulpt/skulpt/blob/master/src/ast.js  
:(

**Comment by albertjan** [comment] 2019-05-22 08:41
ast.js is not a strange place to look. you were on the right track 😄

**Comment by Dustyposa** [comment] 2019-05-22 09:28
I looked the file, doubt the line 346 
`return new Sk.builtin.str(ret);`
Directly  return the `ret` , not use the utf8 coding.
Has any Sk builtin function can make string to be a utf8 string?

**Comment by albertjan** [comment] 2019-05-22 09:42
I think you were right to look in the compiler somehow this string `"这是{}"` got compiled to this constant:

``` 
$scope139.$const141 = new Sk.builtin.str('è¿æ¯\n{}');
```

**Comment by albertjan** [comment] 2019-05-22 09:43
```
print("这是\\n{}")
```

This also breaks.

**Comment by fatpandaria** [comment] 2019-06-25 07:50
Hi guys,hope you will reply me when you see this comment because I don't want to open another issue.It's also about the print(),I just can't print any Chinese like if you call print('中文') ,it will throw a SyntaxError invalid string .This appeared just after I merged the most recent master branch and built the new skulpt.min.js.You can repeat this just in the homepage skulpt editor http://skulpt.org/ and you can see an error in the console panel,while the skulpt editor in the Using Skulpt page is still doing well with Chinese.

**Comment by Dustyposa** [comment] 2019-06-25 08:17
OK, the  latest skulpt-dist file's version is python3?

**Comment by fatpandaria** [comment] 2019-06-25 10:17
Should be python3 but I didn't check it .Can you repeat the problem I met?

**Comment by Dustyposa** [comment] 2019-06-26 01:19
The same problem with 
```python
print("这是\n{}".format("中文"))
>>>è¿�æ�¯
>>>中文
```
I doubt [skulpt-dist](https://github.com/skulpt/skulpt-dist) is not python3 version.
And I build python3 version skulpt need use py27 interpreter?

**Comment by meredydd** [comment] 2019-07-02 10:18
@fatpandaria: The version on the skulpt.org homepage is still python 2. When I do:
```python
print(u'中文')
```
then it works for me.

(The formatting stuff is a separate bug.)

**Comment by albertjan** [comment] 2019-07-02 10:39
@meredydd it's to do with the parsing of strings with escapes in it. you can have unicode or escapes not both :smile:

**Comment by meredydd** [comment] 2019-07-02 11:06
*headdesk*

**Comment by fatpandaria** [comment] 2019-07-02 11:19
@meredydd Thank you,that's kind of a workaround. So there are two versions of Python on the skulpt.org(Home and Using Skulpt). you mean the Home page is still python 2?How about the one in Using Skulpt page which is hosted by trinket and can print Chinese? And the one that  I built with fresh master branch should be Python3 or 2? Will it take long to fix this bug?

**Comment by bnmnetp** [comment] 2019-07-02 16:34
I added ``__future__: "python3"`` to the ``Sk.configure`` call on the home page.  There is no syntax error now.  The example seems to print fine without the newline character, but the newline makes the output look like:

è¿æ¯
中文

**Comment by fatpandaria** [comment] 2019-07-04 04:39
Thanks ,adding  __future__: Sk.python3 to the Sk.configure works for me.

**Comment by Dustyposa** [comment] 2019-07-05 01:20
Yes, if add newline character in format string, and format string include Chinese character. The output will broke.
So, I doubt the format function have something run when string need decode by utf-8.

**Comment by crestin** [comment] 2020-02-01 10:56
Sk.configure({
            output: outf,
            read: builtinRead,
            retainglobals: true,
            **__future__: Sk.python3**
        });

**Closed** 2020-02-21 13:56 UTC
