### ISSUE TITLE
Incorrect handling of *= when used with lists

### ISSUE THREAD

**Issue by AndiPersti** [skulpt/skulpt#278] opened 2014-08-26 10:46 UTC
According to the [language reference](https://docs.python.org/2.6/reference/simple_stmts.html#augmented-assignment-statements), `*=` should be performed in-place when possible, i.e. when the target is a list, it should be modified.

Here's what I get when I use CPython:

    >>> a = [1]
    >>> b = a
    >>> a *= 2
    >>> print(a, b)
    ([1, 1], [1, 1])

Running the same code with Skulpt gives me:

    ([1, 1], [1])

**Comment by waywaaard** [comment] 2015-02-07 11:19
http://stackoverflow.com/a/6794990/1602537

It seems that skulpt currently stores the "value" of an variable at the variable and not referencing it from a global stack.

**Comment by rixner** [comment] 2015-02-07 13:00
Actually, the problem is just that we use the same function for ```*``` and ```*=``` on lists.

https://github.com/skulpt/skulpt/blob/f99349113d17d83ff0e621876960851e92d45d0f/src/list.js#L252-L253

**Comment by waywaaard** [comment] 2015-02-08 13:04
Yeah I've seen this, but does skulpt reference here the same object?

**Comment by rixner** [comment] 2015-02-10 13:15
Yes, the references are correct.  I teach objects and references in Python to students all the time and use Skulpt to do so, so I am quite familiar.  This is not a problem with references, it is simply a problem with our implementation of inplace multiply on lists.

**Comment by rixner** [comment] 2015-02-10 13:17
It would be better to use ```Sk.builtin.list``` to construct a Python list object out of ```ret```.  You forgot to set ```__class__```, for example.  And if we add other things to the constructor in the future, this will make it more trouble to keep things consistent.

**Comment by waywaaard** [comment] 2015-02-10 18:26
The ```__class__``` attribute should remain the same - I am just changing the underlying javascript array holding the values and not the type itself. Otherwise I am not really sure what you mean? It would be possible to work directly with the list methods.

For example ```list_extend``` does also work on the v object and return this, without setting any ```__class__``` attribute

**Comment by rixner** [comment] 2015-02-10 18:55
You are right, I'm incorrect.  I confused myself because instead of extending the current ```this.v```, you created a new one.  I think that should be okay, but is there a reason you decided to create a new array instead of extending the existing one?

**Comment by waywaaard** [comment] 2015-02-10 19:13
No particular reason, though I think I need at least one new array to perform the action, however it could be handled a little bit different.
1. copy original array
2. extend array copy n times with the original value

**Comment by rixner** [comment] 2015-02-10 19:14
Why do you need a copy?  Why can you just do something like:

**Comment by waywaaard** [comment] 2015-02-10 19:19
Yes that's correct, forgot about storing the original length... I thought we would add too many items.

**Comment by waywaaard** [comment] 2015-02-18 22:07
see waywaaard/skulpt:epy@af7c06e858c951bf462da23fa22dea25b1fb3a40

pr incoming soon

**Comment by eah13** [comment] 2015-05-08 13:04
@waywaaard did this PR get merged?  Can we close this issue?

**Comment by waywaaard** [comment] 2015-05-10 18:09
not yet

**Comment by waywaaard** [comment] 2015-09-30 20:02
@bnmnetp This can be closed as the fix is already on the master branch.

```python
a = [1]
b = a
a *= 2
print(a, b)
```

**Comment by eah13** [comment] 2015-09-30 20:06
@waywaaard thx.  These issues definitely need some grooming.  Ping me if brad's not available and I'll get them into shape.  My fault for being scarce since the semester's cranked up

**Closed** 2015-09-30 20:05 UTC
