### ISSUE TITLE
Skulpt rounds down number when handling division

### ISSUE THREAD

**Issue by Anton-Chernyshov** [skulpt/skulpt#1538] opened 2024-01-30 11:04 UTC
When dividing an Integer by another Integer, which would normally return a floating point decimal, returns the integer rounded down, even when trying to ceil it. 

for example:
`import math`
`print(15/8, math.ceil(15/8))`
`print(17/9, math.ceil(17/9))`
`print(3/2, math.ceil(3/2))`

This code returns:
`(1, 1.0)`
`(1, 1.0)`
`(1, 1.0)`
when expected:
`1.875 2`
`1.8888888888888888 2`
`1.5 2`

I am fairly certain this isn't something I did on my end, as all code handing is done through Skulpt, but if somebody else has experienced this and knows how to fix it. Please lmk, although I feel like this is something to do with how Skulpt handles division.

**Comment by s-cork** [comment] 2024-01-30 13:17
Have you tried running your code at skulpt.org?

Seems to work as expected for me. Same for current master branch.

**Comment by Anton-Chernyshov** [comment] 2024-01-30 22:49
Yes, it works on the skulpt.org website, so I dont know why it doesnt work for me? 
the repo where im using it is <a href="https://github.com/Anton-Chernyshov/wIDE">here<a>. It is a very simple frontend so I dont know how this has affected it. Any ideas?

**Comment by s-cork** [comment] 2024-01-30 23:07
Thanks for the source. If you're able to put that in a jsfiddle/codepen or similar it'll be easier to take a look.

**Comment by bnmnetp** [comment] 2024-01-30 23:58
skulpt.org was never intended to be a CDN for loading skulpt javascript.  I just checked and the skulpt.js files there are 4 years old!  I would recommend building your own distribution from our source for your project.

**Comment by Anton-Chernyshov** [comment] 2024-01-31 00:01
hi, <a href="https://jsfiddle.net/AntonChernyshov/pxbzyL28/">here</a> is the jsFiddle for the code, Lines 35-60 are the skulpt code on the js, and the html is at the bottom of the file

**Comment by Anton-Chernyshov** [comment] 2024-01-31 00:03
> skulpt.org was never intended to be a CDN for loading skulpt javascript. I just checked and the skulpt.js files there are 4 years old! I would recommend building your own distribution from our source for your project.

I have been meaning to migrate this to a backend hosted on a raspberry pi, so I will have to look into doing this. Thanks!

**Comment by s-cork** [comment] 2024-01-31 05:14
you could use cdn from jsdeliver

```
<script src="https://cdn.jsdelivr.net/npm/skulpt@1.2.0/dist/skulpt.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/skulpt@1.2.0/dist/skulpt-stdlib.min.js"></script>
```

That should give you the latest published version
closing as this is not a bug in current master

**Closed by s-cork** 2024-01-31 05:14 UTC
