### ISSUE TITLE
Non-english characters in variable name

### ISSUE THREAD

**Issue by darth83** [skulpt/skulpt#1255] opened 2021-01-15 09:34 UTC
I just noticed that it's impossible to use for example 'å ä ö' (Swedish letters) in variables names.

You get: SyntaxError: bad token T_OP on line 1

Is there an easy fix for this?

**Comment by s-cork** [comment] 2021-01-15 10:40
this is a duplicate of #1176 and is currently in progress #1237

**Closed by s-cork** 2021-01-15 10:40 UTC
